### ISSUE TITLE
Pyperclip v1.8.1: KeyError: 'XDG_SESSION_TYPE'

### ISSUE THREAD

**Issue by DattatrayPayatu** [python-cmd2/cmd2#1058]
pyperclip v1.8.1 throw **KeyError: 'XDG_SESSION_TYPE'** error when used with CMD2 v1.3.0 and above. (**pyperclip v1.8.0 is working perfect**.)

```
Traceback (most recent call last):
  File "/usr/local/bin/expliot", line 5, in <module>
    from expliot.expliot import EfCli
  File "/usr/local/lib/python3.8/dist-packages/expliot/expliot.py", line 4, in <module>
    from expliot.core.ui.cli import Cli
  File "/usr/local/lib/python3.8/dist-packages/expliot/core/ui/cli/__init__.py", line 5, in <module>
    from cmd2 import Cmd, with_argument_list
  File "/usr/local/lib/python3.8/dist-packages/cmd2/__init__.py", line 30, in <module>
    from .cmd2 import Cmd
  File "/usr/local/lib/python3.8/dist-packages/cmd2/cmd2.py", line 73, in <module>
    from .clipboard import (
  File "/usr/local/lib/python3.8/dist-packages/cmd2/clipboard.py", line 14, in <module>
    _ = pyperclip.paste()
  File "/usr/local/lib/python3.8/dist-packages/pyperclip/__init__.py", line 680, in lazy_load_stub_paste
    copy, paste = determine_clipboard()
  File "/usr/local/lib/python3.8/dist-packages/pyperclip/__init__.py", line 568, in determine_clipboard
    os.environ["XDG_SESSION_TYPE"] == "wayland" and
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'XDG_SESSION_TYPE'
```

**Comment by tleonhardt** [comment]
@DattatrayPayatu Nothing here seems specific to `cmd2`.  I think you should create an issue in Pyperclip's GitHub and provide more info such as what OS and version you are using.  Unless I'm missing something, this appears to be a bug in `pyperclip` version 1.8.1

**Comment by DattatrayPayatu** [comment]
@tleonhardt, yeah I understand, but pyperclip released the last version in Oct 2020, not sure when they release the fix. Appreciate your help here if it is possible to fix the pyperclip version below 1.8.0 in the next release of cmd2.

**Comment by tleonhardt** [comment]
@DattatrayPayatu Can you please provide more information to help us replicate the issue?

Things the would help include:
- OS name and version (including distro if LInux)
- Terminal name and version
- Shell name and version

Also, if Linux, which of the following do you have installed?
- xclip
- xsel
- gtk
- PyQt4

**Comment by tleonhardt** [comment]
An issue already exists in the Pyperclip repo for this: https://github.com/asweigart/pyperclip/issues/189

Moreover, there is also already a PR to fix it: https://github.com/asweigart/pyperclip/pull/177

**Comment by tleonhardt** [comment]
@DattatrayPayatu Pyperclip 1.8.2 was released a few hours ago with a bug fix for this issue.
