### ISSUE TITLE
cmd2 causes attribute error failure when accessing remote server that uses .casefold()

### ISSUE THREAD

**Issue by tthkbw** [python-cmd2/cmd2#1143]
I have an application developed using the Cmd module. The app connects to a remote server that runs using the rpyc module.

Using Cmd, the applications works reliably. I wanted to update to cmd2. All I changed was the import statement and the Class declaration. The remote server running the rpyc connection was not changed.

The remote server implements an exposed function that uses str.casefold() to do a case insensitive search. 

When the client application is running cmd2, and calls the search function in the remote server, the server reports an Attribute error on trying to access .casefold(). This does not happen when the client is running using Cmd.

```
EXCEPTION of type 'AttributeError' occurred with message: cannot access 'casefold'

========= Remote Traceback (2) =========
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/opt/homebrew/lib/python3.9/site-packages/rpyc/core/protocol.py", line 592, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/Users/tbrown/Documents/projects/BooksGui/rpyc/./BooksServer.py", line 1900, in exposed_FindTitleAuthor
    return FindTitleAuthor(searchstr, False)
  File "/Users/tbrown/Documents/projects/BooksGui/rpyc/./BooksServer.py", line 992, in FindTitleAuthor
    if searchstr.casefold() in book['Title'].casefold() or searchstr.casefold() in book['Author'].casefold():
  File "/opt/homebrew/lib/python3.9/site-packages/rpyc/core/netref.py", line 153, in __getattr__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/opt/homebrew/lib/python3.9/site-packages/rpyc/core/netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "/opt/homebrew/lib/python3.9/site-packages/rpyc/core/protocol.py", line 473, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "/opt/homebrew/lib/python3.9/site-packages/rpyc/core/async_.py", line 102, in value
    raise self._obj
_get_exception_class.<locals>.Derived: cannot access 'casefold'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/opt/homebrew/lib/python3.9/site-packages/rpyc/core/protocol.py", line 608, in _handle_getattr
    return self._access_attr(obj, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/opt/homebrew/lib/python3.9/site-packages/rpyc/core/protocol.py", line 535, in _access_attr
    name = self._check_attr(obj, name, param)
  File "/opt/homebrew/lib/python3.9/site-packages/rpyc/core/protocol.py", line 525, in _check_attr
    raise AttributeError("cannot access %r" % (name,))
AttributeError: cannot access 'casefold'
```

I am running both applications on an M1 Mac mini under Big Sur 11.5.2. Python version 3.9.6. The terminal is iterm2, but the same error occurs using the macOS Terminal.

I don't even know how to start debugging this!

**Comment by tthkbw** [comment]
Okay, I generated some ideas for debugging and quickly found a solution. When I removed .casefold() from the server search, I got a failure, but slightly different:

```
========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/rpyc/core/protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/opt/homebrew/lib/python3.9/site-packages/rpyc/core/protocol.py", line 592, in _handle_call
    return obj(*args, **dict(kwargs))
  File "/Users/tbrown/Documents/projects/BooksGui/rpyc/./BooksServer.py", line 1901, in exposed_FindTitleAuthor
    return FindTitleAuthor(searchstr, False)
  File "/Users/tbrown/Documents/projects/BooksGui/rpyc/./BooksServer.py", line 993, in FindTitleAuthor
    if searchstr in book['Title'] or searchstr in book['Author']:
TypeError: 'in <string>' requires string as left operand, not cmd2.parsing.Statement
```
So, cmd2 is not passing a string to the server when I make the call:

`conn.root.FindTitleAuthor(searchstr`

where 'searchstr' is a string entered at the cmd2 input line.

If, on the server, I cast the input as a string type:

`searchstr = str(searchstr)`

it works.

However, I would like to understand this problem as it is probably a minefield waiting to blow me up on other commands. Is there something I should be doing differently with respect to command parameters when using cmd2 vs Cmd?

**Comment by kmvanbrunt** [comment]
Basic commands in **cmd2** are passed `Statement` objects, which are subclasses of `str`.
https://cmd2.readthedocs.io/en/latest/features/commands.html#statements

Along with the original `str` data, these objects contain custom attributes needed by **cmd2**. The attributes are documented here.
https://cmd2.readthedocs.io/en/latest/api/parsing.html#cmd2.Statement

**Comment by tthkbw** [comment]
Thanks for the explanation, @kmvanbrunt. I confess to not having read the documentation thoroughly before just diving in and simply changing from Cmd to cmd2. I did look at "Incompatibilities" in the documentation and it doesn't seem to mention this case. I was also confused by the initial error trace which didn't identify the typing problem at the server end.

I understand a bit more, now, although I still don't really understand how the Statement type is treated like a String type in the local program, but sent as Statement to the rpyc server and causes a problem there. I must parse the cmd2 arguments before sending them across the link. 

I have seen other interesting typing issues with data transferred via rpyc--primarily where dictionaries transferred were not iterable. 

Thanks again. I am sticking with cmd2, which is quite a powerful addition to my command line tools.

**Comment by anselor** [comment]
@tthkbw I haven't tried looking deeply into what rpyc does to serialize arbitrary objects but my suspicion is that, when confronted with an unknown type, rpyc tries to construct a custom object that mimics the object you're sending by copying the data attributes of the object. I don't think in recognizes or handles the fact that Statement is a subclass of `str` and constructs a custom data object on the server side with the data attributes of `Statement`.
