### ISSUE TITLE
unable to install cmd2-2.3.3 from github tarball, pypi tarball, or wheel on fedora 35

### ISSUE THREAD

**Issue by jonez734** [python-cmd2/cmd2#1191]
- the 'pyperclip' package has been renamed to 'pyclip'. changing this in the setup file did not result in a successful build.
- fedora 35 with all updates
- python 3.10

```
[~/tmp/cmd2-2.3.3] [7:28pm] [jam@cyclops] % ./setup.py wheel cmd2-2.3.3-py3-none-any.whl 
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
Traceback (most recent call last):
  File "/home/jam/tmp/cmd2-2.3.3/./setup.py", line 93, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.10/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 455, in __init__
    _Distribution.__init__(self, {
  File "/usr/lib64/python3.10/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 807, in finalize_options
    ep(self)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/home/jam/tmp/cmd2-2.3.3/.eggs/setuptools_scm-6.4.0-py3.10.egg/setuptools_scm/integration.py", line 75, in version_keyword
    _assign_version(dist, config)
  File "/home/jam/tmp/cmd2-2.3.3/.eggs/setuptools_scm-6.4.0-py3.10.egg/setuptools_scm/integration.py", line 51, in _assign_version
    _version_missing(config)
  File "/home/jam/tmp/cmd2-2.3.3/.eggs/setuptools_scm-6.4.0-py3.10.egg/setuptools_scm/__init__.py", line 102, in _version_missing
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for /home/jam/tmp/cmd2-2.3.3.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Comment by kmvanbrunt** [comment]
`pyclip` appears unrelated to `pyperclip` (e.g. different authors, different codebase).
Also, `pyclip` requires Python 3.7+. `cmd2` needs to support Python 3.6+.
