### ISSUE TITLE
AttributeError: module 'cmd2' has no attribute '__version__' when built with pyinstaller

### ISSUE THREAD

**Issue by terrysimons** [python-cmd2/cmd2#1198]
Hi there,

I'm building a cmd2 app with pyinstaller for both macOS and Windows.

On macOS, when running the python sources natively, everything works fine.

When building as a pyinstaller app, the cmd2 app works fine, except when I run a script with the -t option I get an error such as:

```
================================================= cmd2 transcript test =================================================
Traceback (most recent call last):
  File "hift_b1.py", line 8, in <module>
  File "cmd2\cmd2.py", line 5270, in cmdloop
  File "cmd2\cmd2.py", line 4987, in _run_transcript_tests
AttributeError: module 'cmd2' has no attribute '__version__'
[3068] Failed to execute script 'hift_b1' due to unhandled exception!
```

This happens on Windows (above) as well as macOS:
```
=================================== cmd2 transcript test ====================================
Traceback (most recent call last):
  File "hift_b1.py", line 8, in <module>
    b1_shell.cmdloop()
  File "cmd2/cmd2.py", line 5270, in cmdloop
  File "cmd2/cmd2.py", line 4987, in _run_transcript_tests
AttributeError: module 'cmd2' has no attribute '__version__'
[20091] Failed to execute script 'hift_b1' due to unhandled exception!
```

Just curious if any of the cmd2 app developers have familiarity with this, since I would have expected the module to fail outright if it wasn't getting imported by pyinstaller.

How is the `__version__` parameter handled in cmd2?  Is there some magic there that might be getting missed by pyinstaller perhaps?

Thanks,

-Terry

**Comment by terrysimons** [comment]
I looked at the source and saw how the __version__ property is managed.  That explains the problem I ran into.

The fix is to add this to the pyinstaller build step:

`--collect-all cmd2`

Interestingly enough while it seemed like `--hidden-import importlib` *should* work, it does not, nor does `--collect-submodules cmd2`

Hopefully this helps someone else!

Cheers,

- Terr
