### ISSUE TITLE
Question: overriding built-in alias command

### ISSUE THREAD

**Issue by kulikjak** [python-cmd2/cmd2#1214]
This is more of a question than an issue.

In an older version of cmd2 (0.9.13), I was able to override `do_alias` method (and not use alias functionality provided not any arguments for the command) simply with:
```python
    def do_alias(self, arg):
        print("alias command")
```
however, with version 2.4.0, the same code results in the following error:
```
Traceback (most recent call last):
  File "interactive.py", line 13, in <module>
    cmd = SStoreCmd()
  File "/usr/lib/python3.7/vendor-packages/cmd2/cmd2.py", line 529, in __init__
    self._register_subcommands(self)
  File "/usr/lib/python3.7/vendor-packages/cmd2/cmd2.py", line 808, in _register_subcommands
    f"Could not find argparser for command '{command_name}' needed by subcommand: {str(method)}"
cmd2.exceptions.CommandSetRegistrationError: Could not find argparser for command 'alias' needed by subcommand: <bound method Cmd._alias_create of <__main__.MyCmd object at 0x7fefc3565810>>
```
Is this expected behavior? And what would be the optimal solution to this? I did some testing managed to get back with the following, but I don't know if this is the best way to do so (or if I am just hiding other issues with this):
```python
    parser = argparse.ArgumentParser()
    @with_argparser(parser, with_unknown_args=True)
    def do_alias(self, arg, opt):
        print("alias command")
```

**Comment by kmvanbrunt** [comment]
Your solution works and I don't think it will lead to errrors. But if you want to override `do_alias` without needing an `argparse` decorator, do something like this.

```Python
class App(cmd2.Cmd):
    def __init__(self, *args, **kwargs) -> None:
        # Delete subcommand functions which expect do_alias to have an argparser
        del cmd2.Cmd._alias_create
        del cmd2.Cmd._alias_delete
        del cmd2.Cmd._alias_list

        # Call cmd2's __init__() after deleting the subcommand functions
        super().__init__(*args, **kwargs)

    def do_alias(self, arg):
        print("alias command")
```
