### ISSUE TITLE
overiding perror crashes program for unrecognized errors

### ISSUE THREAD

**Issue by rADikal8e7** [python-cmd2/cmd2#1250]
I am trying to log all commands from my application to a log file. Based on the recommendation by @kmvanbrunt in the following discussion #1248 overwriting the `poutput` works. However trying the same for `perror` causes the program to crash if it encounters an unrecognized command.

**command used**
exit

**Code used:**
```
    # parse commands into the main log file.
    def _postparsing_hook(self, data: cmd2.plugin.PostparsingData) -> cmd2.plugin.PostparsingData:
        """Log the prompt and typed command. This runs right after the command line is parsed."""

        # Handle multiline commands by restoring continuation_prompts
        command_line = data.statement.raw.replace("\n", f"\n{self.continuation_prompt}")
        logger.info(f"{self.prompt}{command_line}")
        return data

    def poutput(self, msg: Any = '', *, end: str = '\n') -> None:
        """Override poutput() to log all data before calling the parent"""

        # Remove ansi style characters (e.g. color) which we don't want in the log file
        # This originally was "{msg}{end}", but that printed too many newlines in the log file.
        # So you might want to mess with the formatting to fit your preference.
        to_log = cmd2.ansi.strip_style(f"{msg}")
        logger.info(to_log)
        super().poutput(msg, end=end)

    def perror(self, msg: Any = '', *, end: str = '\n') -> None:
        """Override perror() to log all data before calling the parent"""

        # Remove ansi style characters (e.g. color) which we don't want in the log file
        # This originally was "{msg}{end}", but that printed too many newlines in the log file.
        # So you might want to mess with the formatting to fit your preference.
        to_log = cmd2.ansi.strip_style(f"{msg}")
        logger.info(to_log)
        super().perror(msg, end=end)
```

**Error hit**

```
saft>exit
Traceback (most recent call last):
  File "/root/Desktop/poetry_cache/virtualenvs/nexus-qa-saft-fyT_f9Ml-py3.9/lib/python3.9/site-packages/cmd2/cmd2.py", line 2399, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/root/Desktop/poetry_cache/virtualenvs/nexus-qa-saft-fyT_f9Ml-py3.9/lib/python3.9/site-packages/cmd2/cmd2.py", line 2853, in onecmd
    stop = self.default(statement)
  File "/root/Desktop/poetry_cache/virtualenvs/nexus-qa-saft-fyT_f9Ml-py3.9/lib/python3.9/site-packages/cmd2/cmd2.py", line 2872, in default
    self.perror(err_msg, apply_style=False)
TypeError: perror() got an unexpected keyword argument 'apply_style'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/Desktop/nexus-qa-saft/src/saft/cli.py", line 424, in cli
    sys.exit(c.cmdloop())
  File "/root/Desktop/poetry_cache/virtualenvs/nexus-qa-saft-fyT_f9Ml-py3.9/lib/python3.9/site-packages/cmd2/cmd2.py", line 5282, in cmdloop
    self._cmdloop()
  File "/root/Desktop/poetry_cache/virtualenvs/nexus-qa-saft-fyT_f9Ml-py3.9/lib/python3.9/site-packages/cmd2/cmd2.py", line 3140, in _cmdloop
    stop = self.onecmd_plus_hooks(line)
  File "/root/Desktop/poetry_cache/virtualenvs/nexus-qa-saft-fyT_f9Ml-py3.9/lib/python3.9/site-packages/cmd2/cmd2.py", line 2439, in onecmd_plus_hooks
    self.pexcept(ex)
  File "/root/Desktop/poetry_cache/virtualenvs/nexus-qa-saft-fyT_f9Ml-py3.9/lib/python3.9/site-packages/cmd2/cmd2.py", line 1132, in pexcept
    self.perror(final_msg, end=end, apply_style=False)
TypeError: perror() got an unexpected keyword argument 'apply_style'
```

**Expected Behavior**
```
saft>exit
exit is not a recognized command, alias, or macro
```

**Comment by rADikal8e7** [comment]
Apologies. typo on my end. I seem to have picked the wrong `perror` definition. Fixing that got `perror` working as expected. 

```
    def perror(self, msg: Any = '', *, end: str = '\n', apply_style: bool = True) -> None:
        """Override perror() to log all data before calling the parent"""

        # Remove ansi style characters (e.g. color) which we don't want in the log file
        # This originally was "{msg}{end}", but that printed too many newlines in the log file.
        # So you might want to mess with the formatting to fit your preference.
        to_log = cmd2.ansi.strip_style(f"{msg}")
        logger.info(to_log)
        super().perror(msg, end=end)
```

**Comment by kmvanbrunt** [comment]
The call to `perror()` is missing the `apply_style` argument. It should be:
`super().perror(msg, end=end, apply_style=apply_style)`

**Comment by kmvanbrunt** [comment]
The call to `perror()` is missing the `apply_style` argument. It should be:
```Python
super().perror(msg, end=end, apply_style=apply_style)
```
