### ISSUE TITLE
CMD2 gives Error 'width must be at least 1' When using Columnize to order a list of items with long names

### ISSUE THREAD

**Issue by KassOst** [python-cmd2/cmd2#1255]
**Issue:**
The strings are too long to make a table with the values and fails with the error `EXCEPTION of type 'ValueError' occurred with message: width must be at least 1`

**Additional details:**
This occurs during the columnize function that counts the characters of multiple strings at once and makes sure that it doesn't go over the width of the screen. (set as 79 characters) 

If it does go over the width it sets the column width as 0. That 0 is passed into the align_left() then into align_text() function that then fails with the error that the width is 0.

https://github.com/python-cmd2/cmd2/blob/e95af81acb9c6829c969f76e40658356a4808edb/cmd2/cmd2.py#L3693

The problem is that the width of the strings of the list values goes over that 79 when placed side by side, but instead of showing it in a straight list it fails since the column width was set to 0. 

Changing the `0` to `None` and it is then it is able to load the list with no issues as one column. 

**Full traceback:**
```
Traceback (most recent call last):
  File "/home/kassandra/builder/virtualenv/lib/python3.9/site-packages/cmd2/cmd2.py", line 2398, in onecmd_plus_hooks
    stop = self.onecmd(statement, add_to_history=add_to_history)
  File "/home/kassandra/builder/virtualenv/lib/python3.9/site-packages/cmd2/cmd2.py", line 2849, in onecmd
    stop = func(statement)
  File "/home/kassandra/builder/virtualenv/lib/python3.9/site-packages/cmd2/decorators.py", line 379, in cmd_wrapper
    return func(*args_list, **kwargs)  # type: ignore[call-arg]
  File "/home/kassandra/builder/virtualenv/lib/python3.9/site-packages/cmd2/cmd2.py", line 3603, in do_help
    self._help_menu(args.verbose)
  File "/home/kassandra/builder/virtualenv/lib/python3.9/site-packages/cmd2/cmd2.py", line 3721, in _help_menu
    self._print_topics(category, cmds_cats[category], verbose)
  File "/home/kassandra/builder/virtualenv/lib/python3.9/site-packages/cmd2/cmd2.py", line 3763, in _print_topics
    self.print_topics(header, cmds, 15, 80)
  File "/home/kassandra/builder/virtualenv/lib/python3.9/site-packages/cmd2/cmd2.py", line 3649, in print_topics
    self.columnize(cmds, maxcol - 1)
  File "/home/kassandra/builder/virtualenv/lib/python3.9/site-packages/cmd2/cmd2.py", line 3705, in columnize
    texts[col] = utils.align_left(texts[col], width=colwidths[col])
  File "/home/kassandra/builder/virtualenv/lib/python3.9/site-packages/cmd2/utils.py", line 981, in align_left
    return align_text(text, TextAlignment.LEFT, fill_char=fill_char, width=width, tab_width=tab_width, truncate=truncate)
  File "/home/kassandra/builder/virtualenv/lib/python3.9/site-packages/cmd2/utils.py", line 869, in align_text
    raise ValueError("width must be at least 1")
ValueError: width must be at least 1
EXCEPTION of type 'ValueError' occurred with message: width must be at least 1
```

**Comment by kmvanbrunt** [comment]
@KassOst Thanks for the bug report. This error has now been fixed. Install cmd2 2.4.3 for the updated code.
