### ISSUE TITLE
Can't run first application example

### ISSUE THREAD

**Issue by burbilog** [python-cmd2/cmd2#1296]
Can't run First application from the documentation at cmd2.readthedocs.io:

~~~
#!/usr/bin/env python
"""A simple cmd2 application."""
import cmd2


class FirstApp(cmd2.Cmd):
    """A simple cmd2 application."""


if __name__ == '__main__':
    import sys
    c = FirstApp()
    sys.exit(c.cmdloop())
~~~

I tried both debian11 (python 3.9.2) and ubuntu 23.10 (python 3.11.6 and 3.11.3), tried installing python3-cmd2 (2.4.3+ds-2) from ubuntu repo and 2.4.3 from pip. Everything fails in the same way:

~~~
Traceback (most recent call last):
File "/home/rm/cmd.py", line 14, in <module>
import cmd2
File "/home/rm/.virtualenvs/test/lib/python3.11/site-packages/cmd2/__init__.py", line 53, in <module>
from .cmd2 import Cmd
File "/home/rm/.virtualenvs/test/lib/python3.11/site-packages/cmd2/cmd2.py", line 32, in <module>
import cmd
File "/home/rm/cmd.py", line 17, in <module>
class CmdLineApp(cmd2.Cmd):
^^^^^^^^
AttributeError: partially initialized module 'cmd2' has no attribute 'Cmd' (most likely due to a circular import)
~~~

Other cmd2 examples fail as well.

**Comment by burbilog** [comment]
Aww, nevermind, I called the example cmd.py and that's why circular dependence...
