### ISSUE TITLE
Piping output to input of os command causes unhandled exception on Python 3.x

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#35]
The output redirection feature where command output can be piped (|) as input to operating-system commands, as in "help | wc" is broken for Python 3.x but still works for Python 2.7.  This feature's expected behavior is documented here:
https://cmd2.readthedocs.io/en/latest/freefeatures.html#output-redirection

Not only is it broken, but it causes an unhandled exception.  It appears to be a str (unicode) vs bytes issue.

When "debug" is set to True, this is the exception I got:
(Cmd) help | wc
Traceback (most recent call last):
  File "/Users/toddleonhardt/src/cmd2/cmd2.py", line 872, in onecmd_plus_hooks
    stop = self.onecmd(statement)
  File "/Users/toddleonhardt/src/cmd2/cmd2.py", line 955, in onecmd
    stop = func(statement)
  File "/Users/toddleonhardt/src/cmd2/cmd2.py", line 543, in do_help
    cmd.Cmd.do_help(self, arg)
  File "/Users/toddleonhardt/anaconda/lib/python3.5/cmd.py", line 333, in do_help
    self.stdout.write("%s\n"%str(self.doc_leader))
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toddleonhardt/src/cmd2/cmd2.py", line 877, in onecmd_plus_hooks
    self.restore_output(statement)
  File "/Users/toddleonhardt/src/cmd2/cmd2.py", line 928, in restore_output
    self.kept_state.stdout.write(result or '')
TypeError: write() argument must be str, not bytes

**Comment by tleonhardt** [comment]
This has been fixed.  The subprocess module is particularly bad in terms of being able to play nicely with unicode or byte strings.  Some features were added in Python 3.5 to make it easier, but prior to that you need to be exquisitely careful how you send data to or get data from a subprocess via stdin/stdout/stderr.
