### ISSUE TITLE
Sphinx autodoc API documentation is currently broken

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#479]
All of the embedded *autodoc* API documentation is missing from the [cmd2 docs](http://cmd2.readthedocs.io/en/latest/index.html).

Typically when this occurs it means that we have added a new required dependency and we forgot to add that to the documentation [requirements.txt](https://github.com/python-cmd2/cmd2/blob/master/docs/requirements.txt)

This same issue has occurred a number of times before.  We should consider trying to add a unit test for the build of the Sphinx HTML documentation to make sure some of the API documentation is present and/or that the docs can build with no significant errors/warnings.

**Comment by tleonhardt** [comment]
I'm 95% sure we just need to add ``attrs`` to the docs\requirements.txt

**Comment by tleonhardt** [comment]
*sigh* docs are broken again.  The recent switch to using ``setuptools_scm`` for version number broke the ReadTheDocs build of our Sphinx documentation.

Error log is below:
```sh
python /home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v1.7.6

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 64, in <module>
    version = get_distribution('cmd2').version
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 468, in get_distribution
    dist = get_provider(dist)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 344, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cmd2' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 167, in __init__
    raise ConfigError(CONFIG_ERROR % traceback.format_exc())
sphinx.errors.ConfigError: There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 64, in <module>
    version = get_distribution('cmd2').version
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 468, in get_distribution
    dist = get_provider(dist)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 344, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cmd2' distribution was not found and is required by the application


Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 64, in <module>
    version = get_distribution('cmd2').version
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 468, in get_distribution
    dist = get_provider(dist)
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 344, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/docs/checkouts/readthedocs.org/user_builds/cmd2/envs/latest/lib/python3.5/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cmd2' distribution was not found and is required by the application
```
