### ISSUE TITLE
AppVeyor Windows CI is currently broken

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#678]
[Here](https://ci.appveyor.com/project/FedericoCeratto/cmd2/builds/24519892) is an example of a recent AppVeyor run of our Windows unit tests.  We haven't changed our AppVeyor config file in many months, so whatever broke it happened on AppVeyor's end.

The build actually runs forever (or a very long time) and need to be manually cancelled.

**Comment by tleonhardt** [comment]
Taking a look at likely possible culprits, `tox` version 3.10 just got published to PyPI today, May 13.  The [tox changelog](https://github.com/tox-dev/tox/blob/master/docs/changelog.rst) has some interesting notes, including this "feature":
> Virtual environments created now no longer upgrade pip/wheel/setuptools to the latest version. Instead the start packages after virtualenv creation now is whatever virtualenv has bundled in. This allows faster virtualenv creation and builds that are easier to reproduce. 

So we might need to simply upgrade pip to the latest version and then use that newer version to upgrade wheel and setuptools.  Chances are decent that the Linux environments we use on TravisCI and the macOS environments we use on AzurePipelines are more up to date than the Windows environments we use on AppVeyor.

**Comment by tleonhardt** [comment]
# Failures
I tried various changes on the *appveyor_fix* branch and none of them worked.  

It appears that the failures are different for different versions of windows.

## Python 3.5
For Python 3.5 it appears to be failing because it no longer properly recognizes the optional test requirement for `mock` for python versions prior to 3.6.
```sh
%PYTHON%/python -m tox -e %TOXENV%
37GLOB sdist-make: C:\projects\cmd2\setup.py
38py35 create: C:\projects\cmd2\.tox\py35
39py35 inst: C:\projects\cmd2\.tox\.tmp\package\1\cmd2-0.9.13.dev51+gb3d0aac.zip
40ERROR: invocation failed (exit code 2), logfile: C:\projects\cmd2\.tox\py35\log\py35-1.log
41================================== log start ==================================
42Processing c:\projects\cmd2\.tox\.tmp\package\1\cmd2-0.9.13.dev51+gb3d0aac.zip
43  Requirement already satisfied (use --upgrade to upgrade): cmd2==0.9.13.dev51+gb3d0aac from file:///C:/projects/cmd2/.tox/.tmp/package/1/cmd2-0.9.13.dev51%2Bgb3d0aac.zip in c:\projects\cmd2
44Exception:
45Traceback (most recent call last):
46  File "C:\projects\cmd2\.tox\py35\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2610, in _dep_map
47    return self.__dep_map
48  File "C:\projects\cmd2\.tox\py35\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2685, in __getattr__
49    raise AttributeError(attr)
50AttributeError: _Distribution__dep_map
51
52During handling of the above exception, another exception occurred:
53
54Traceback (most recent call last):
55  File "C:\projects\cmd2\.tox\py35\lib\site-packages\pip\basecommand.py", line 209, in main
56    status = self.run(options, args)
57  File "C:\projects\cmd2\.tox\py35\lib\site-packages\pip\commands\install.py", line 310, in run
58    wb.build(autobuilding=True)
59  File "C:\projects\cmd2\.tox\py35\lib\site-packages\pip\wheel.py", line 748, in build
60    self.requirement_set.prepare_files(self.finder)
61  File "C:\projects\cmd2\.tox\py35\lib\site-packages\pip\req\req_set.py", line 360, in prepare_files
62    ignore_dependencies=self.ignore_dependencies))
63  File "C:\projects\cmd2\.tox\py35\lib\site-packages\pip\req\req_set.py", line 647, in _prepare_file
64    set(req_to_install.extras) - set(dist.extras)
65  File "C:\projects\cmd2\.tox\py35\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2810, in extras
66    return [dep for dep in self._dep_map if dep]
67  File "C:\projects\cmd2\.tox\py35\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2624, in _dep_map
68    dm.setdefault(extra,[]).extend(parse_requirements(reqs))
69  File "C:\projects\cmd2\.tox\py35\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2980, in parse_requirements
70    "version spec")
71  File "C:\projects\cmd2\.tox\py35\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 2945, in scan_list
72    raise RequirementParseError(msg, line, "at", line[p:])
73pip._vendor.pkg_resources.RequirementParseError: Expected version spec in mock ; python_version<'3.6' at  ; python_version<'3.6'
```

## Python 3.6
For Python 3.6 it appears that all tests pass and then at the end, it gets a keyboard interrupt signal and is waiting for someone at a terminal to hit "Y" to finish:
```sh
==================== 578 passed, 5 skipped in 5.06 seconds ====================
88ERROR: got KeyboardInterrupt signal
89___________________________________ summary ___________________________________
90ERROR:   py36: keyboardinterrupt
91Terminate batch job (Y/N)? 
```

## Python 3.7
It never gets here because it gets stuck with Python 3.6

**Comment by tleonhardt** [comment]
## Python 3.7
So if I comment out running the Python 3.6 tests, then the Python 3.7 ones run and pass without getting stuck.
