### ISSUE TITLE
Errors while running from console

### ISSUE THREAD

**Issue by HynekPetrak** [python-cmd2/cmd2#768]
Hi, how shall I run a cmd2 application from within an ssh session (no xwindows) . I get the below errors

Traceback (most recent call last):
  File "/usr/local/bin/sshame", line 11, in <module>
    load_entry_point('sshame', 'console_scripts', 'sshame')()
  File "/root/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/root/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/root/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/sshame/sshame/main.py", line 6, in <module>
    import cmd2
  File "/usr/local/lib/python3.7/dist-packages/cmd2-0.9.16-py3.7.egg/cmd2/__init__.py", line 15, in <module>
    from .cmd2 import Cmd, Statement, EmptyStatement, categorize
  File "/usr/local/lib/python3.7/dist-packages/cmd2-0.9.16-py3.7.egg/cmd2/cmd2.py", line 51, in <module>
    from .clipboard import can_clip, get_paste_buffer, write_to_paste_buffer
  File "/usr/local/lib/python3.7/dist-packages/cmd2-0.9.16-py3.7.egg/cmd2/clipboard.py", line 12, in <module>
    _ = pyperclip.paste()
  File "/usr/lib/python3/dist-packages/pyperclip/__init__.py", line 663, in lazy_load_stub_paste
    copy, paste = determine_clipboard()
  File "/usr/lib/python3/dist-packages/pyperclip/__init__.py", line 554, in determine_clipboard
    return init_gi_clipboard()
  File "/usr/lib/python3/dist-packages/pyperclip/__init__.py", line 163, in init_gi_clipboard
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

**Comment by HynekPetrak** [comment]
DISPLAY=:0

**Comment by kotfu** [comment]
Your use case should work. Can you try something for me to see if we can chase down the problem? Over that same ssh connection, try this from a shell prompt, and please paste the entire output of all commands to this thread:
```
$ python
>>> import pyperclip
```

**Comment by kotfu** [comment]
Scratch that, I don't need you to run the `import pyperclip` command above. I think I've solved the issue. `pyperclip` on linux needs certain python libraries so it can talk to GTK. If you are using ubuntu or one of it's variants, you can install these libraries by:
```
$ sudo apt install python3-gi gobject-introspection gir1.2-gtk-3.0
```
If you are on some other flavor of linux, you need to figure out how to install the [PyGobject](https://pygobject.readthedocs.io/en/latest/) libraries.

See https://stackoverflow.com/questions/56823857/valueerror-namespace-gtk-not-available for more info

**Comment by HynekPetrak** [comment]
```
# python3
Python 3.7.4 (default, Aug 21 2019, 16:01:23)
[GCC 9.2.1 20190813] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyperclip
>>>
```

**Comment by HynekPetrak** [comment]
```
# sshame
Traceback (most recent call last):
  File "/usr/local/bin/sshame", line 11, in <module>
    load_entry_point('sshame', 'console_scripts', 'sshame')()
  File "/root/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/root/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/root/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/sshame/sshame/main.py", line 6, in <module>
    import cmd2
  File "/usr/local/lib/python3.7/dist-packages/cmd2-0.9.16-py3.7.egg/cmd2/__init__.py", line 15, in <module>
    from .cmd2 import Cmd, Statement, EmptyStatement, categorize
  File "/usr/local/lib/python3.7/dist-packages/cmd2-0.9.16-py3.7.egg/cmd2/cmd2.py", line 51, in <module>
    from .clipboard import can_clip, get_paste_buffer, write_to_paste_buffer
  File "/usr/local/lib/python3.7/dist-packages/cmd2-0.9.16-py3.7.egg/cmd2/clipboard.py", line 12, in <module>
    _ = pyperclip.paste()
  File "/usr/lib/python3/dist-packages/pyperclip/__init__.py", line 663, in lazy_load_stub_paste
    copy, paste = determine_clipboard()
  File "/usr/lib/python3/dist-packages/pyperclip/__init__.py", line 554, in determine_clipboard
    return init_gi_clipboard()
  File "/usr/lib/python3/dist-packages/pyperclip/__init__.py", line 163, in init_gi_clipboard
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

**Comment by HynekPetrak** [comment]
What if you catch any Exception or at least the ValueError too?

```
# Can we access the clipboard?  Should always be true on Windows and Mac, but only sometimes on Linux
try:
    # Try getting the contents of the clipboard
    _ = pyperclip.paste()
except PyperclipException:
    can_clip = False
else:
    can_clip = True
```

**Comment by tleonhardt** [comment]
@HynekPetrak 
Fundamentally, I view this as a bug in `pyperclip`.  As such, I would encourage you to create an [Issue](https://github.com/asweigart/pyperclip/issues) there if you haven't already.

That being said, since it is affecting `cmd2` users, it would be reasonable for us to also catch `ValueError`  as you suggested.
