### ISSUE TITLE
ValueError exception when loading history file

### ISSUE THREAD

**Issue by vjangus** [python-cmd2/cmd2#785]
cmd2 version = 0.9.16
Python version = 3.6
OS name and version = Windows 10
What you did to cause the bug to occur = A history file that was created by an old version of cmd2 (<=0.9.14) caused an exception during initialization and the upgraded cmd2 crashed

Include any traceback or error message associated with the bug = 

```
Traceback (most recent call last):
  File "C:\Users\mattthk4\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\mattthk4\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mattthk4\cvenv\Scripts\cdata-cli.exe\__main__.py", line 9, in <module>
  File "c:\users\mattthk4\cvenv\lib\site-packages\cbash\cdata_cli.py", line 1193, in main
    app = CmdLineApp(debug=args.debug)
  File "c:\users\mattthk4\cvenv\lib\site-packages\cbash\cdata_cli.py", line 274, in __init__
    cmd2.Cmd.__init__(self, persistent_history_file=self.HIST_FILE)
  File "c:\users\mattthk4\cvenv\lib\site-packages\cmd2\cmd2.py", line 429, in __init__
    self._initialize_history(persistent_history_file)
  File "c:\users\mattthk4\cvenv\lib\site-packages\cmd2\cmd2.py", line 3602, in _initialize_history
    history = pickle.load(fobj)
ValueError: invalid literal for int() with base 10: 'et projects --p\n'
```

Cause: The call to pickle.load() in cmd2._initialize_history() failed to catch the ValueError exception.

Solution: Add ValueError in the list of non-operating system error/exception to catch.

Proposed changes:

```
diff --git a/cmd2/cmd2.py b/cmd2/cmd2.py
index 5e1f9a7..5831053 100644
--- a/cmd2/cmd2.py
+++ b/cmd2/cmd2.py
@@ -3592,7 +3592,7 @@ class Cmd(cmd.Cmd):
         try:
             with open(hist_file, 'rb') as fobj:
                 history = pickle.load(fobj)
-        except (AttributeError, EOFError, FileNotFoundError, ImportError, IndexError, KeyError, pickle.UnpicklingError):
+        except (AttributeError, EOFError, FileNotFoundError, ImportError, IndexError, KeyError, pickle.UnpicklingError, ValueError):
             # If any non-operating system error occurs when attempting to unpickle, just use an empty history
             pass
         except OSError as ex:
```

**Comment by tleonhardt** [comment]
@vjangus Hey Victor, thank you for reporting this issue.

This appears to clearly be a bug on our part for an edge case we had not yet encountered.  We will work on getting a fix out shortly.

**Comment by vjangus** [comment]
The fix looks good. Thank you.
