### ISSUE TITLE
AppVeyor tests acting up

### ISSUE THREAD

**Issue by tleonhardt** [python-cmd2/cmd2#836]
Windows CI testing on AppVeyor is currently failing with a `UnicodeDecodeError`.  However, @kmvanbrunt manually ran the tests on Windows without any issue:
```sh
py37 run-test: commands[0] | py.test --cov --junitxml=junit/test-results.xml
56Traceback (most recent call last):
57  File "c:\miniconda37-x64\Lib\runpy.py", line 193, in _run_module_as_main
58    "__main__", mod_spec)
59  File "c:\miniconda37-x64\Lib\runpy.py", line 85, in _run_code
60    exec(code, run_globals)
61  File "C:\projects\cmd2\.tox\py37\Scripts\py.test.EXE\__main__.py", line 7, in <module>
62  File "c:\projects\cmd2\.tox\py37\lib\site-packages\_pytest\config\__init__.py", line 72, in main
63    config = _prepareconfig(args, plugins)
64  File "c:\projects\cmd2\.tox\py37\lib\site-packages\_pytest\config\__init__.py", line 223, in _prepareconfig
65    pluginmanager=pluginmanager, args=args
66  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pluggy\hooks.py", line 286, in __call__
67    return self._hookexec(self, self.get_hookimpls(), kwargs)
68  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
69    return self._inner_hookexec(hook, methods, kwargs)
70  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
71    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
72  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pluggy\callers.py", line 203, in _multicall
73    gen.send(outcome)
74  File "c:\projects\cmd2\.tox\py37\lib\site-packages\_pytest\helpconfig.py", line 89, in pytest_cmdline_parse
75    config = outcome.get_result()
76  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pluggy\callers.py", line 80, in get_result
77    raise ex[1].with_traceback(ex[2])
78  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pluggy\callers.py", line 187, in _multicall
79    res = hook_impl.function(*args)
80  File "c:\projects\cmd2\.tox\py37\lib\site-packages\_pytest\config\__init__.py", line 793, in pytest_cmdline_parse
81    self.parse(args)
82  File "c:\projects\cmd2\.tox\py37\lib\site-packages\_pytest\config\__init__.py", line 999, in parse
83    self._preparse(args, addopts=addopts)
84  File "c:\projects\cmd2\.tox\py37\lib\site-packages\_pytest\config\__init__.py", line 957, in _preparse
85    early_config=self, args=args, parser=self._parser
86  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pluggy\hooks.py", line 286, in __call__
87    return self._hookexec(self, self.get_hookimpls(), kwargs)
88  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
89    return self._inner_hookexec(hook, methods, kwargs)
90  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
91    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
92  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pluggy\callers.py", line 208, in _multicall
93    return outcome.get_result()
94  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pluggy\callers.py", line 80, in get_result
95    raise ex[1].with_traceback(ex[2])
96  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pluggy\callers.py", line 187, in _multicall
97    res = hook_impl.function(*args)
98  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pytest_cov\plugin.py", line 118, in pytest_load_initial_conftests
99    plugin = CovPlugin(early_config.known_args_namespace, early_config.pluginmanager)
100  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pytest_cov\plugin.py", line 164, in __init__
101    self.start(engine.Central)
102  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pytest_cov\plugin.py", line 186, in start
103    self.cov_controller.start()
104  File "c:\projects\cmd2\.tox\py37\lib\site-packages\pytest_cov\engine.py", line 179, in start
105    config_file=self.cov_config)
106  File "c:\projects\cmd2\.tox\py37\lib\site-packages\coverage\control.py", line 193, in __init__
107    concurrency=concurrency, context=context,
108  File "c:\projects\cmd2\.tox\py37\lib\site-packages\coverage\config.py", line 516, in read_coverage_config
109    config_read = config.from_file(fname, our_file=our_file)
110  File "c:\projects\cmd2\.tox\py37\lib\site-packages\coverage\config.py", line 327, in from_file
111    self._config_contents = f.read()
112  File "c:\projects\cmd2\.tox\py37\lib\encodings\cp1252.py", line 23, in decode
113    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
114UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 635: character maps to <undefined>
115ERROR: InvocationError for command 'C:\projects\cmd2\.tox\py37\Scripts\py.test.EXE' --cov --junitxml=junit/test-results.xml (exited with code 1)
116___________________________________ summary ____________________________
```

**Comment by tleonhardt** [comment]
These tests work fine for `coverage` version 4.5.4 but fail for `coverage` 5.0 or 5.0.1 when all other dependencies are held constant.
