### ISSUE TITLE
The do_shell() is not working correctly with multiple commands

### ISSUE THREAD

**Issue by legacy-code** [python-cmd2/cmd2#986]
When I call do_shell() with multiple commands using 

* ";".join(commands) - it only executes the first command
* "&&".join(commands) - it throws an exception

Given the following script (which has all of the details), you can see the behavior I'm seeing.

```python

#!/usr/bin/env python

"""A simple cmd2 application."""
import cmd2


class App(cmd2.Cmd):
    """
    A simple cmd2 application.  Copied from "Basic Commands" in the manual.

    I had a LOT of Cmd apps/scripts that I was using and then converted most
    of them to use Cmd2 and all was working fine with this type of formatting,
    (i.e. multiple commands in a string).
    
    At some point, after updating to different versions of cmd2, many of my 
    commands started breaking like this one does.  
    
    I can run SINGLE commands, but not multiple ones -- especially when I just
    "join" them from multiple lines to one line.  Note though, in the "works"
    command, I use just a string passed into *do_shell* and it works, which 
    surprised me.  If I try that with a ";" as the seperator, it does not work,
    which is what happens in the "fail1" and "fail2" commands.
    
    I haven't dived into the why, but was able to replicate it quite easily in 
    something that is pretty small (the comments and me explaining it are 
    probably going to be much longer than the actual code).

    Both failures should work just fine, as they are commands that will work
    from:
    
        * the bash prompt 
        * the Cmd2 shell prompt (i.e. using !<command>)
        * the Cmd.do_shell() function (using Cmd, not Cmd2)
        
    I use commands like this all the time.  Cmd's do_shell() handles
    this as expected.  Even Cmd2's command prompt handles the exact same 
    commands just fine.

    If I type something like the following commands, FROM the Cmd2/App command 
    prompt, they work as expected, so ...

        - !echo "hi";echo "there";echo "cmd2"
        - !echo "hi"&&echo "there"
        - !ls && echo "-----done-----"
        
    I'm not sure where a regression came in at.  If needed, I can go back to
    the different versions that I'm pretty sure it was working and give it a
    try.

    This used to work in Cmd2 as well, until a little while ago.  I've not
    narrowed down the exact date, but I think it's sometime around the new 
    addition of the CommandSet changes (which I was surprised to find and 
    wanted to use).  
    
    It was around that time (after CommandSet introduction to the code base), 
    so pretty sure it's after v1.2.1.  It's probably after v1.3.0 or v1.3.1, as 
    I had it working and didn't see any problems with it.  Multiple commands 
    doing just this were added at around that time as well.
    
    I THINK was after v1.3.1, around the time that the CommandSet stuff broke 
    backward compatibility with itself (as I remember thinking I didn't realize
    I was working on such the cutting edge! ;-) ) and I skipped at least one 
    version if not more, so can't say when, for sure, it broke this functionality.
    
    It was definitely broken after v1.3.4.  I upgraded to v1.3.5 today 
    (2020-08-27) to see if it had been fixed.  I wasn't terribly surprised that
    it still was broken.
    
    Now for some system information:
    
        OS:     macOS Catalina v10.15.5
        Python: v3.8.0
        Cmd2:   v1.3.5
    """

    # common commands to show problem
    cmds = [
        'echo "hi"',
        'echo "there"',
        'echo "cmd2!"'
    ]

    def __init__(self):
        super().__init__()
        self.debug = True

    def _printMessage(self, cmd):
        print(f"\n\n-----cmd=[{cmd}]-----")
        print("this fails in 'self.do_shell(cmd)'")
        print(f"BUT, it works if you do [!{cmd}] from the (Cmd) prompt\n\n")

    def do_fail1(self, statementObj):
        # this should work (and used to work),
        # but ONLY executes the FIRST command - ignores the rest
        cmd = ';'.join(self.cmds)

        self._printMessage(cmd)
        self.do_shell(cmd)

    def do_fail2(self, statementObj):
        # this should also work - better bash 'best practice' anyway
        # this just fails though
        cmd = '&&'.join(self.cmds)

        self._printMessage(cmd)
        self.do_shell(cmd)

    def do_works(self, statementObj):
        print("\n")
        self.do_shell('echo "this works just fine!"')
        print("\nas does this! \n")
        self.do_shell('ls -la')
        print("\nthis surprisingly DOES work -- not sure why :-( \n")
        self.do_shell('ls&&echo "-----done-----"')
        print("\n")

if __name__ == '__main__':
    import sys
    c = App()
    sys.exit(c.cmdloop())
```

Thanks!
Mike

**Comment by legacy-code** [comment]
Here is the error I'm getting for _do_fail1()_ (I realized that I had forgotten to paste that in the sample - sorry):

```python
(Cmd) fail1
    
-----cmd=[echo "hi";echo "there";echo "cmd2!"]-----
this fails in 'self.do_shell(cmd)'
BUT, it works if you do [!echo "hi";echo "there";echo "cmd2!"] from the (Cmd) prompt

Traceback (most recent call last):
 File "/Users/bea704/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cmd2/cmd2.py", line 2023, in onecmd_plus_hooks
   stop = self.onecmd(statement, add_to_history=add_to_history)
 File "/Users/bea704/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cmd2/cmd2.py", line 2453, in onecmd
   stop = func(statement)
 File "./tst2.py", line 118, in do_fail1
   self.do_shell(cmd)
 File "/Users/bea704/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cmd2/decorators.py", line 309, in cmd_wrapper
   args_list = _arg_swap(args, statement, *new_args)
 File "/Users/bea704/.pyenv/versions/3.8.0/lib/python3.8/site-packages/cmd2/decorators.py", line 72, in _arg_swap
   index = args.index(search_arg)
ValueError: tuple.index(x): x not in tuple
EXCEPTION of type 'ValueError' occurred with message: 'tuple.index(x): x not in tuple'
(Cmd)
```

**Comment by legacy-code** [comment]
I quickly reverted back to v1.2.1 and it worked.  

Upgraded to v1.3.0 and it did NOT work.  

So, something change between these two versions.

Hope that helps!

-Mike

**Comment by kmvanbrunt** [comment]
For the multiple shell command, question, cmd2 treats `;` as a command terminator. It's used to terminate multiline commands. Anything that appears after a semicolon is removed during cmd2 command line parsing. If you have no multiline commands, pass an empty list for the terminators argument.

```Python
def __init__(self):
    super().__init__(terminators = [])
    self.debug = True
```

**Comment by anselor** [comment]
I found a small issue specifically when processing multiple commands on a single line and with_argparse. Need to see about getting this reproduced in a unit test and then I can put up a fix.

**Comment by legacy-code** [comment]
That would be awesome, as a large majority of the commands I use internally in cmd/cmd2 are multiple commands in a single line.

Thanks!

**Comment by kmvanbrunt** [comment]
If your app does not implement any multiline commands, then disabling terminators makes sense.

**Comment by anselor** [comment]
It's some sort of interaction between the terminator, calling do_shell, and with_argparse. I'm not seeing it with other instances of multiple commands on a single with `;` as a separator. I have a simple test that copies the failure example above and verifies that it no longer crashes.

**Comment by legacy-code** [comment]
@kmvanbrunt - I don't have any right now, but I do want to add some, so ...

Hard choices!  😀  

Right now, I've just reverted back to v1.2.1 as it works and I need that over other features right now.  I'll have to give it a try though later.  Maybe this weekend.

I also want to use the CommandSet stuff, which started me on this whole thing, as I usually don't pay too close of attention to new features or updates, unless something breaks or I realize I'm a bunch of versions behind the latest.  😆

**Comment by anselor** [comment]
@legacy-code I have a PR is up that no longer crashes with your example. Can you try it out?

**Comment by legacy-code** [comment]
@anselor what about the "&&"?  

After noticing that the ";" was failing, I realized that really I should be using "&&" chaining so that if something fails, just quit.  That's probably safer (for what I'm doing anyway).

**Comment by kmvanbrunt** [comment]
@legacy-code If you want both the ability to chain shell commands with semicolons and plan to have multiline commands, then just choose another terminator character.

**Comment by legacy-code** [comment]
@kmvanbrunt that would work!  Thanks.  I'll give it a go soon!

Thanks again to you and @anselor for your quick response!

**Comment by anselor** [comment]
@legacy-code I tried both of your examples.

**Comment by legacy-code** [comment]
Thanks @anselor -- I saw the unit test!  

Great!  Thanks again for your help!

**Comment by anselor** [comment]
@legacy-code What version of python are you using?

For me, your `fail2` command doesn't produce the crash that the `fail1` command does.

**Comment by anselor** [comment]
Nevermind, I see you provided that info.
